index:
    path: /
    controller: App\Controller\AdminController::index

#route de deconnexion
app_logout:
    path: /logout


app_register:
    path: /admin/register
    controller: App\Controller\RegistrationController::register

#route de connexion
app_login:
    path: /login
    controller: App\Controller\SecurityController::login

#accueil des etudiants
etudiantAccueil:
    path: /etudiant/accueil/{etudiant_id}
    controller: App\Controller\EtudiantController::accueilEtudiant
    
#accueil des enseignants
enseignantAccueil:
    path: /enseignant/accueil/{enseignant_id}
    controller: App\Controller\EnseignantController::accueilEnseignant

#Consulter les informations d'un étudiant
etudiantConsulter:
    path: /etudiant/etudiant/consulter/{etudiant_id}
    controller: App\Controller\EtudiantController::consultoModifierEtudiant

#Consulter les informations d'un enseignant
enseignantConsulter:
    path: /enseignant/consulter/{enseignant_id}
    controller: App\Controller\EnseignantController::consultoModifierEnseignant


        # Route concernant admin

admin:
    path: /admin
    controller: App\Controller\AdminController::admin

#accueil admin
adminAccueil:
    path: /admin/accueil
    controller: App\Controller\AdminController::accueil

#ajouter un etudaint
etudiantAjouter:
    path: /admin/ajouterEtudiant
    controller: App\Controller\AdminController::ajouterEtudiant

#ajouter un enseignant
enseignantAjouter:
    path: /admin/ajouterEnseignant
    controller: App\Controller\AdminController::ajouterEnseignant

#lister les etudiant
listerEtudiant:
    path: /admin/listerEtudiant
    controller: App\Controller\AdminController::listerEtudiant

#lister les enseignant
listerEnseignant:
    path: /admin/listerEnseignant
    controller: App\Controller\AdminController::listerEnseignant

#Reinitailisation du mdp enseignant
MDPDefaultEnseignant:
    path: /admin/REmdpEnseignant/{user_id}
    controller: App\Controller\AdminController::REmpdEnseignant

#Reinitailisation du mdp etudiant   
MDPDefaultEtudiant:
    path: /admin/REmdpEtudiant/{user_id}
    controller: App\Controller\AdminController::REmpdEtudiant

#Consulto-Modifier Etudiant   
ConsulterEtudiantAdmin:
    path: /admin/ConsulterEtudiantAdmin/{user_id}
    controller: App\Controller\AdminController::ConsulterEtudiantAdmin

#Consulto-Modifier Enseignant  
ConsulterEnseignantAdmin:
    path: /admin/ConsulterEnseignantAdmin/{user_id}
    controller: App\Controller\AdminController::ConsulterEnseignantAdmin

#Supprimer Enseignant  
SupprimerEnseignantAdmin:
    path: /admin/SupprimerEnseignantAdmin/{user_id}
    controller: App\Controller\AdminController::SupprimerEnseignantAdmin    

        # Route concernant RP ( etudiant )

#RPPDF
rpPDF:
    path: etudiant/rp/pdf/{rp_id}
    controller: App\Controller\RPController::rpPDF        

#Ajouter une RP
rpAjouter:
    path: etudiant/rp/ajouter/{etudiant_id}
    controller: App\Controller\RPController::ajouterRp
    
#lister mes RP (etudiant)
etudiantListerLesRP:
    path: /etudiant/rp/listerMesRP/{etudiant_id}
    controller: App\Controller\RPController::listerLesRP
    
#Lister RP archiver
rpListerArchiver:
    path: etudiant/rp/ListerArchivage/{etudiant_id}
    controller: App\Controller\RPController::listerRPArchiver    

#ArchiverRP
rpArchivage:
    path: etudiant/rp/archivage/{rp_id}
    controller: App\Controller\RPController::archiveRP

#supprimer d'une RP
rpDelete:
    path: /etudiant/rp/deleteRp/{rp_id}
    controller: App\Controller\RPController::deleteRp

#restorer d'une RP
rpRestore:
    path: /etudiant/rp/restoreRp/{rp_id}
    controller: App\Controller\RPController::restoreRp

#consulter une RP d'un étudiant
rpConsulter:
    path: /etudiant/rp/consulter/{rp_id}
    controller: App\Controller\RPController::consultoModifierRP

#consulter un commentaire d'une RP
rpConsulterCommentaire:
    path: /etudiant/rp/consulterCommentaire/{rp_id}
    controller: App\Controller\RPController::consulterCommentaireRPEtudiant

#consulter les activité d'une RP
rpConsulterActivite:
    path: /etudiant/rp/consulterActivite/{rp_id}
    controller: App\Controller\RPController::consulterActiviteRPEtudiant

#supprimer une activite d'une RP
rpDeleteActivite:
    path: /etudiant/rp/deleteActivite/{rpActivite_id}
    controller: App\Controller\RPController::deleteActivite

#Modif une activite d'une RP
rpModifierActivite:
    path: /etudiant/rp/modifierActivite/{rpActivite_id}
    controller: App\Controller\RPController::modifierRPActivite

#consulter les production d'une RP
rpConsulterProduction:
    path: /etudiant/rp/consulterProduction/{rp_id}
    controller : App\Controller\RPController::consulterProductionRPEtudiant

#supprimer une production d'une RP
rpDeleteProduction:
    path: /etudiant/rp/deleteProduction/{production_id}
    controller: App\Controller\RPController::deleteProduction

#Modif une production d'une RP
rpModifierProduction:
    path: /etudiant/rp/modifierProduction/{production_id}
    controller: App\Controller\RPController::modifierProduction

#lister les RP à modifier (etudiant)
etudiantLesRPaModifier:
    path: /etudiant/rp/listerLesRPaModifier/{etudiant_id}
    controller: App\Controller\RPController::listerLesRPaModifier

#Ajouter des activités à une RP
ajouterActiviteRP:
    path: /etudiant/rp/ajouterActivite/{rp_id}
    controller: App\Controller\RPController::ajouterActiviteRP

#Ajouter des productions à une RP
ajouterProductionRP:
    path: /etudiant/rp/ajouterProduction/{rp_id}
    controller: App\Controller\RPController::ajouterProductionRP
    
#PDF des RP pour le bloc 1
rpPDFB1:
    path: /etudiant/rp/pdfB1/{etudiant_id}
    controller: App\Controller\RPController::pdfB1

        # Route concernant RP ( prof )

#lister les RP à commenter (prof)
enseignantLesRPaCommenter:
    path: /enseignant/rp/listerLesRPaCommenter/{enseignant_id}
    controller: App\Controller\RPController::listerLesRPaCommenter

#lister les RP (prof)
listerRPPromo:
    path: /enseignant/rp/listerLesRP
    controller: App\Controller\RPController::listerLesRPPromo


#valider une rp (prof)
viseRP:
    path: /enseignant/rp/visee/{rp_id}
    controller: App\Controller\RPController::ValiderRP

#Modif un commentaire d'une RP
rpModifierCommentaire:
    path: /enseignant/rp/modifierCommentaire/{commentaire_id}
    controller: App\Controller\RPController::modifierCommentaire
      
#supprimer un commentaire d'une RP
rpDeleteCommentaire:
    path: /enseignant/rp/deleteCommentaire/{commentaire_id}
    controller: App\Controller\RPController::deleteCommentaire


        # Route concernant les stages ( etudiant )

#lister les stages d'un etudiant
EtudiantListerStage:
    path: /etudiant/stage/listerLesStages/{etudiant_id}
    controller: App\Controller\StageController::ListerStagesEtudiant

#consulter les infos de stage d'un étudiant
StageConsulter:
    path: /etudiant/stage/consulter/{stage_id}
    controller: App\Controller\StageController::consultoModifierStage

#Ajouter un stage ( etudiant )    
stageAjouter:
    path: /stage/ajouter/{etudiant_id}
    controller: App\Controller\StageController::ajouterStage

#consulter les semaine d'un stage
ConsulterSemaineStage:
    path: /etudiant/stage/consulterSemaine/{semaine_id}
    controller: App\Controller\StageController::consulterSemaineStage

deleteTacheSemaine:
    path: /etudiant/stage/deleteTacheSemaine/{tache_id}
    controller: App\Controller\StageController::deleteTache

#Modif une tache d'une semaine de stage
ModifierTacheSemaine:
    path: /etudiant/stage/modifierTache/{tache_id}
    controller: App\Controller\StageController::modifierTache

#consulter les pointage d'un stage
PointageStage:
    path: /etudiant/stage/pointage/{stage_id}
    controller: App\Controller\StageController::pointageStage

#consulter les echanges d'un stage
EchangeStage:
    path: /etudiant/stage/echange/{stage_id}
    controller: App\Controller\StageController::echangeStage  

#PDF du semaine de stage
PdfSemaine:
    path: /etudiant/stage/pdfSemaine/{semaine_id}
    controller: App\Controller\StageController::pdfSemaine  

#PDF attesation de stage
PdfAttestation:
    path: /etudiant/stage/pdfAttestation/{stage_id}
    controller: App\Controller\StageController::pdfAttestation  

        # Route concernant les stages ( prof )

#Visualiser les stages en cours qui me sont affecté (prof)
ListerStagesAffect:
    path: /enseignant/stage/ListerStagesAffect/{enseignant_id}
    controller: App\Controller\StageController::ListerStagesAffect

#Lister les stages des étudiants d'une promotion sélectionnée
stagePromo:
  path: /enseignant/stage/listerStagePromo/{promotion_id}
  controller: App\Controller\StageController::ListerStagesPromo

#Lister les anciens stage
ListerAncienStages:
    path: /etudiant/stage/ListerAncienStages
    controller: App\Controller\StageController::ListerAncienStages

#Affecter les stages non affecter
ListerStages:
    path: /enseignant/stage/ListerStages
    controller: App\Controller\StageController::ListerStages





